update nginx.conf to block plex news
toomuchio/plex-nginx-reverseproxy pull request #28
Opened 2017-10-02 16:57 UTC by zenjabba

Given people are not comfortable with Plex News, this can disable it on  your end clients without any modifications to the clients. (v1.9.2 PlexServer)

2017-10-02 21:49 UTC, toomuchio commented
Plex News? Do you have a screenshot of the before and after of what this does? I've never seen it before.

2017-10-02 21:50 UTC, zenjabba commented
https://www.reddit.com/r/PleX/comments/73ord0/remove_plex_news_with_nginx_reverse_proxy/ <https://www.reddit.com/r/PleX/comments/73ord0/remove_plex_news_with_nginx_reverse_proxy/>

> On 2 Oct 2017, at 5:49 pm, Too Much IO <notifications@github.com> wrote:
> 
> Plex News? Do you have a screenshot of the before and after of what this does? I've never seen it before.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/toomuchio/plex-nginx-reverseproxy/pull/28#issuecomment-333675282>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AApfuLlDuM0UeWbAAGD_tzH4duMNMeJmks5soVpfgaJpZM4Pq77S>.
>

2017-10-02 23:04 UTC, toomuchio requested changes
Switch to spaces instead of tabs, you need to add.
Under line 81.
``#Disables compression between Plex and Nginx, required for sub_filter
#proxy_set_header Accept-Encoding "";``

84 change to: #Example of sub_filter to alter what Plex displays, this disables Plex News.

I'll approve that I guess.

2017-10-03 00:56 UTC, merged

2017-10-03 01:01 UTC, toomuchio commented
Merged very cool hack I was using something similar very early on to try and display messages to people but didn't work out well.

Might be work investigating manipulation of the xml to display alerts to users, creating fake librarys or menu options perhaps to alert people of changes to your Plex server.

2018-01-08 22:32 UTC, sander1 commented
This is nice :) I have added this to my config:

```
location / {
	sub_filter '</body>' '<script src="/my.js"></script></body>';
	sub_filter_once on;
}
```

Now the web interface loads and also loads my added .js file, in which I can do some nice and/or funny things. For example set/change some of Plex Web's preferences:
- Set _Time Format_ to display a 24 hour clock;
- Set _Video Quality_ to "Maximum".

```
(function() {
	if (typeof(Storage) !== "undefined") {
		var experience = {"timeFormat": "HH:mm", "remoteQuality": "-1"};
		localStorage.setItem("experience", JSON.stringify(experience));
	}
})();
```

Note: This only works if people visit my PMS through my own domain, not through plex.tv